---

- hosts: docker_hosts
  become: true
  vars_files:
    - application_vars.yml

  tasks:
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'curl', 'python3-pip', 'virtualenv', 'python3-setuptools', 'network-manager']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Pull default Application Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    # Pulling Monitoring Agent Image
    - name: Pull default Application Docker image
      docker_image:
        name: "quay.io/prometheus/node-exporter:latest"
        source: pull
    
    # Deploying Monitoring Agent Container
    - name: Create Moniroting Agent Container
      docker_container:
        name: "prometheus-node"
        image: "quay.io/prometheus/node-exporter:latest"
        detach: yes
        ports:
          - "9100:9100"
        volumes:
          - "/:/host:ro,rslave"
        state: started
        restart_policy: unless-stopped

    # Creates the number of containers defined by the variable create_containers, using values from vars file
    - name: Create default Application containers
      docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image }}"
        detach: yes
        ports:
          - "8{{ item }}:80"
        state: started
        restart_policy: unless-stopped
      with_sequence: start=0 end="{{ create_containers - 1}}"

    # Disable management NIC (used to apply updates, deploy docker and its images.)
    # - name: Disable Management NIC
    #   net_interface:
    #     name: ens33
    #     description: down