---

docker_hosts:
  hosts:
%{ for app_srv in APPSERVERS ~}
    docker_host0${app_srv.name}:
      ansible_host: ${APPSERVICEAZ0CIDR}.${app_srv.name}
      ansible_user: ${LINUXUSER}
%{ endfor ~}
%{ for app_srv in APPSERVERS ~}
    docker_host1${app_srv.name}:
      ansible_host: ${APPSERVICEAZ1CIDR}.${app_srv.name}
      ansible_user: ${LINUXUSER}
%{ endfor ~}    docker_host121:
      ansible_host: 172.16.1.21
      ansible_user: ubuntu
    docker_host020:
      ansible_host: 172.16.0.20
      ansible_user: ubuntu
    docker_host120:
      ansible_host: 172.16.1.20
      ansible_user: ubuntu
    docker_host021:
      ansible_host: 172.16.0.21
      ansible_user: ubuntu
